import type { IconType } from 'react-icons';
import {
  LuTriangleAlert,
  LuBell,
  LuBellOff,
  LuBookOpen,
  LuCalculator,
  LuCalendar,
  LuCalendarDays,
  LuCalendarRange,
  LuCamera,
  LuCheck,
  LuChevronRight,
  LuClipboardList,
  LuCopy,
  LuCreditCard,
  LuDownload,
  LuFile,
  LuFileText,
  LuFlag,
  LuFlaskConical,
  LuGamepad2,
  LuGift,
  LuGlobe,
  LuGraduationCap,
  LuCircleHelp,
  LuHouse,
  LuImage,
  LuLayoutDashboard,
  LuLink,
  LuMapPin,
  LuMedal,
  LuMegaphone,
  LuMessageSquare,
  LuMic,
  LuMonitor,
  LuEllipsis,
  LuPackage,
  LuPalette,
  LuPaperclip,
  LuPartyPopper,
  LuPhone,
  LuPin,
  LuPlus,
  LuPuzzle,
  LuReply,
  LuSchool,
  LuSearch,
  LuSettings,
  LuShield,
  LuSmartphone,
  LuSparkles,
  LuStar,
  LuTarget,
  LuTicket,
  LuTrendingUp,
  LuTrophy,
  LuTv,
  LuUpload,
  LuUser,
  LuUsers,
  LuVideo,
  LuWallet,
  LuWifiOff,
  LuX,
} from 'react-icons/lu';

export const ICON_NAMES = [
  'layoutDashboard',
  'school',
  'plus',
  'creditCard',
  'user',
  'video',
  'graduationCap',
  'puzzle',
  'gift',
  'package',
  'calendar',
  'trophy',
  'ticket',
  'shield',
  'flag',
  'smartphone',
  'palette',
  'calendarDays',
  'settings',
  'bookOpen',
  'users',
  'download',
  'alertTriangle',
  'calendarRange',
  'fileText',
  'target',
  'trendingUp',
  'upload',
  'megaphone',
  'clipboardList',
  'home',
  'messageSquare',
  'bell',
  'moreHorizontal',
  'check',
  'wifiOff',
  'camera',
  'paperclip',
  'mapPin',
  'image',
  'x',
  'chevronRight',
  'copy',
  'reply',
  'mic',
  'file',
  'link',
  'pin',
  'bellOff',
  'search',
  'wallet',
  'globe',
  'helpCircle',
  'tv',
  'gamepad2',
  'medal',
  'partyPopper',
  'sparkles',
  'flaskConical',
  'calculator',
  'monitor',
  'star',
  'phone',
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export const ICON_MAP: Record<IconName, IconType> = {
  layoutDashboard: LuLayoutDashboard,
  school: LuSchool,
  plus: LuPlus,
  creditCard: LuCreditCard,
  user: LuUser,
  video: LuVideo,
  graduationCap: LuGraduationCap,
  puzzle: LuPuzzle,
  gift: LuGift,
  package: LuPackage,
  calendar: LuCalendar,
  trophy: LuTrophy,
  ticket: LuTicket,
  shield: LuShield,
  flag: LuFlag,
  smartphone: LuSmartphone,
  palette: LuPalette,
  calendarDays: LuCalendarDays,
  settings: LuSettings,
  bookOpen: LuBookOpen,
  users: LuUsers,
  download: LuDownload,
  alertTriangle: LuTriangleAlert,
  calendarRange: LuCalendarRange,
  fileText: LuFileText,
  target: LuTarget,
  trendingUp: LuTrendingUp,
  upload: LuUpload,
  megaphone: LuMegaphone,
  clipboardList: LuClipboardList,
  home: LuHouse,
  messageSquare: LuMessageSquare,
  bell: LuBell,
  moreHorizontal: LuEllipsis,
  check: LuCheck,
  wifiOff: LuWifiOff,
  camera: LuCamera,
  paperclip: LuPaperclip,
  mapPin: LuMapPin,
  image: LuImage,
  x: LuX,
  chevronRight: LuChevronRight,
  copy: LuCopy,
  reply: LuReply,
  mic: LuMic,
  file: LuFile,
  link: LuLink,
  pin: LuPin,
  bellOff: LuBellOff,
  search: LuSearch,
  wallet: LuWallet,
  globe: LuGlobe,
  helpCircle: LuCircleHelp,
  tv: LuTv,
  gamepad2: LuGamepad2,
  medal: LuMedal,
  partyPopper: LuPartyPopper,
  sparkles: LuSparkles,
  flaskConical: LuFlaskConical,
  calculator: LuCalculator,
  monitor: LuMonitor,
  star: LuStar,
  phone: LuPhone,
};

export function getRewardCategoryIcon(category: string): IconName {
  if (category === 'digital') return 'gift';
  if (category === 'experience') return 'sparkles';
  return 'package';
}

export function getSubjectIcon(subjectId: string): IconName {
  if (subjectId.includes('math')) return 'calculator';
  if (subjectId.includes('science')) return 'flaskConical';
  if (subjectId.includes('english')) return 'bookOpen';
  if (subjectId.includes('ict')) return 'monitor';
  return 'bookOpen';
}
